version: "3.3"

services:
  openfire:
    image: ghcr.io/pojiro/openfire:4.7.4
    ports:
      - "5222:5222"
      - "9090:9090"
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:13.10
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: {}
